// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "a2461183-ea97-4374-bc7c-d7ef28b8125b");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1604501044);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1604501038);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1604501033);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 97);
user_pref("browser.newtabpage.activity-stream.impressionId", "{23bba427-4cab-44ea-aa38-28180afd0c49}");
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1604501040810");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1604522640810");
user_pref("browser.search.region", "RO");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1604501037");
user_pref("browser.slowStartup.averageTime", 7755);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201028150324");
user_pref("browser.startup.homepage_override.mstone", "82.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1604501035);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"managed-bookmarks\",\"personal-bookmarks\"]},\"seen\":[\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1604501044903");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "82.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "e50ea66cf56a4e2893c2169260f5da4e");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "82.0.2");
user_pref("extensions.lastPlatformVersion", "82.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3cf492bd-4e0b-4dd4-9b71-debecf5f3e2b\",\"formautofill@mozilla.org\":\"a0b25d28-1d1d-45c6-86e4-22f5f743f8ee\",\"screenshots@mozilla.org\":\"afa6eb58-5875-4ba7-95f4-e10544db9793\",\"webcompat-reporter@mozilla.org\":\"012bacf6-8c6e-4dcf-b8ca-4a07724c4b9e\",\"webcompat@mozilla.org\":\"79ea96aa-775e-4a87-b344-acc547404d7e\",\"addon@darkreader.org\":\"facf5eb4-3aae-4676-87f3-e9e2b6ad47f5\",\"uBlock0@raymondhill.net\":\"372ccc40-80bd-4fe2-83a2-4ee50a021724\",\"default-theme@mozilla.org\":\"0d6305bf-41d8-468a-9e4e-398e18df405e\",\"google@search.mozilla.org\":\"1a3fb7c6-f8c6-4ea1-beb0-7c2a52ee10ab\",\"amazondotcom@search.mozilla.org\":\"05272302-e393-4ced-9daa-52265e0806a9\",\"wikipedia@search.mozilla.org\":\"ca4c1b85-8679-440e-993b-1848bbbaf201\",\"bing@search.mozilla.org\":\"d1547ef1-90fe-42c9-88de-bb717b51b728\",\"ddg@search.mozilla.org\":\"740b26d0-da2b-494f-a2eb-82dace15d280\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 59935);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "54912c77-a8ce-435d-9f6a-1fa0b1cdaf7e");
user_pref("security.sandbox.plugin.tempDirSuffix", "c3a70302-f62e-46cf-a5d5-5c3ef1a42558");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.startup.last_success", 1604501029);
user_pref("toolkit.telemetry.cachedClientID", "00661026-83c7-4d70-9bd1-6ff112a59f6d");
user_pref("toolkit.telemetry.previousBuildID", "20201028150324");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
